services:

  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile
    container_name: aiko_web_ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - aiko_net

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: aiko_llm
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - aiko_net

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: aiko_chat
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - aiko_net

networks:
  aiko_net:
    driver: bridge